library(HIEv)
setToken()
myDates <- read.csv('data/crapyDates.csv')
myDates$Date <- dmy(as.character(myDates$Date))
ROSnames <- paste0('data/ROS/', list.files('data/ROS/'))
ROS <- plyr::rbind.fill(lapply(ROSnames, readTOA5))
ROSdate <- dplyr::summarise(dplyr::group_by(ROS, Date), Tmean=mean(AirTC_Avg),
                            Tmax=max(AirTC_Avg), Tmin=min(AirTC_Avg), PARmax=max(PPFD_Avg),
                             PARtotal=sum(PPFD_Avg*5*60/1e06))
tableS1 <- dplyr::left_join(myDates, ROSdate, by='Date')
write.csv(tableS1, file='output/tableS1.csv', row.names = F)
source('scripts/updateChamber13C_calc.R')
deltaPairedPre$Date <- as.Date(deltaPairedPre$start)
summChams <- dplyr::summarise(dplyr::group_by(deltaPairedPre, Date, chamberTDL), length(start))
wtc <- data.table::fread('data/WTC_TEMP_CM_WTCFLUX_20130910-20140530_L1_v1.csv')
wtc$DateTime <- ymd_hms(wtc$DateTime)
wtc$datetimeFM <- nearestTimeStep(wtc$DateTime, 15, 'ceiling')
wtc2 <- dplyr::summarise(dplyr::group_by(wtc, datetimeFM), PARmean=mean.na(PAR))
wtc2$Date <- as.Date(wtc2$datetimeFM)
wtcDate <- dplyr::summarise(dplyr::group_by(wtc2, Date), PPFDtotal=sum(PARmean*15*60/1e6))
write.csv(wtcDate, file='output/moreDataForFigS1.csv', row.names = F)
rm(myDates, ROS, ROSnames, ROSdate, tableS1, wtc, wtc2, wtcDate)